export const VULNERABILITY_QUESTIONS: string[] = [
  "What's one thing you're afraid to face in your recovery?",
  "Who have you hurt the most, and what would you say to them right now?",
  "What's a lie you've told yourself to justify using?",
  "What's the hardest thing about being honest with yourself?",
  "If you could redo one moment in your life, what would it be?",
  "What are you most grateful for today that you didn't have a year ago?",
  "What's one thing you haven't forgiven yourself for?",
  "What does surrender mean to you personally?",
  "What's your biggest fear about staying sober?",
  "Who do you need to make amends to, and what's stopping you?",
  "What was your rock bottom moment?",
  "What's one thing people here don't know about you?",
  "What does community mean to you now versus before treatment?",
  "What's the most courageous thing you've done in recovery?",
  "What would your life look like in five years if you stay on this path?",
  "What emotion is hardest for you to sit with?",
  "What's one boundary you need to set but haven't?",
  "How has your relationship with yourself changed in recovery?",
  "What's a coping mechanism you're still working on letting go of?",
  "What would you tell someone who's where you were six months ago?",
];
