export const DEFAULT_WORDS: string[] = [
  "airlock",
  "alibi",
  "amnesty",
  "antidote",
  "armada",
  "avalanche",
  "ballad",
  "beacon",
  "blizzard",
  "bunker",
  "carousel",
  "catacomb",
  "cathedral",
  "cavern",
  "chandelier",
  "citadel",
  "constellation",
  "contraband",
  "courtyard",
  "crossroads",
  "cyclone",
  "decoy",
  "dynasty",
  "eclipse",
  "embassy",
  "epitaph",
  "exile",
  "fossil",
  "fountain",
  "frontier",
  "gargoyle",
  "geyser",
  "glacier",
  "gondola",
  "grotto",
  "hangar",
  "hideout",
  "hologram",
  "hourglass",
  "iceberg",
  "illusion",
  "insomnia",
  "javelin",
  "kaleidoscope",
  "labyrinth",
  "lagoon",
  "lighthouse",
  "lullaby",
  "manuscript",
  "marathon",
  "masquerade",
  "menagerie",
  "meteor",
  "mirage",
  "moat",
  "monastery",
  "monsoon",
  "mosaic",
  "nomad",
  "nostalgia",
  "oasis",
  "obelisk",
  "observatory",
  "orchard",
  "paradox",
  "pendulum",
  "periscope",
  "pilgrimage",
  "pinnacle",
  "quarantine",
  "quarry",
  "quicksand",
  "ransom",
  "relic",
  "riddle",
  "sabotage",
  "sanctuary",
  "scaffold",
  "serpent",
  "silhouette",
  "smuggler",
  "stalemate",
  "stowaway",
  "summit",
  "sundial",
  "tapestry",
  "telescope",
  "tornado",
  "trapeze",
  "treason",
  "tribunal",
  "tsunami",
  "tundra",
  "turbulence",
  "undertow",
  "vertigo",
  "vortex",
  "voyage",
  "wilderness",
  "windmill",
  "zeppelin",
];

// ---------------------------------------------------------------------------
// Short, plain-language descriptions shown to non-imposters alongside the word
// so a player who doesn't know it can still give a clue. Keyed by word (lower-
// case). Custom words added in Settings simply won't have a description.
// ---------------------------------------------------------------------------

export const WORD_DESCRIPTIONS: Record<string, string> = {
  airlock:
    "A sealed chamber between two spaces (like on a spaceship) so air can't escape.",
  alibi: "Proof you were somewhere else when something happened.",
  amnesty: "An official pardon — letting people off without punishment.",
  antidote: "Something that cancels out a poison or fixes a problem.",
  armada: "A large fleet of warships.",
  avalanche: "A huge mass of snow sliding fast down a mountain.",
  ballad: "A slow song that tells a story, often about love.",
  beacon: "A light or signal used as a guide or warning.",
  blizzard: "A severe snowstorm with strong winds.",
  bunker: "A reinforced underground shelter.",
  carousel: "A merry-go-round — a spinning ride with horses.",
  catacomb: "Underground tunnels used as burial places.",
  cathedral: "A large, important church.",
  cavern: "A big cave.",
  chandelier: "A hanging light fixture with many bulbs or crystals.",
  citadel: "A fortress that protects a city.",
  constellation: "A pattern of stars in the night sky.",
  contraband: "Goods that are illegal to own or trade.",
  courtyard: "An open area enclosed by walls or buildings.",
  crossroads: "Where two roads meet — a point of big decision.",
  cyclone: "A powerful spinning windstorm.",
  decoy: "Something used to lure or distract — a fake.",
  dynasty: "A line of rulers from the same family.",
  eclipse: "When one space object blocks another's light — the sun or moon goes dark.",
  embassy: "The office of one country's representatives in another country.",
  epitaph: "Words written on a gravestone.",
  exile: "Being forced to live away from your home country.",
  fossil: "Preserved remains of an ancient plant or animal in rock.",
  fountain: "A structure that shoots water up for decoration.",
  frontier: "The edge of settled land — an unexplored border.",
  gargoyle: "A carved stone monster on the edge of a building.",
  geyser: "A spring that shoots hot water and steam into the air.",
  glacier: "A slow-moving river of ice.",
  gondola: "A long, narrow boat poled through the canals of Venice.",
  grotto: "A small, scenic cave.",
  hangar: "A large building where aircraft are kept.",
  hideout: "A secret place to hide.",
  hologram: "A 3-D image made with light.",
  hourglass: "A glass timer where sand falls from top to bottom.",
  iceberg: "A huge floating chunk of ice in the sea.",
  illusion: "Something that fools the eye or mind — not what it seems.",
  insomnia: "Not being able to sleep.",
  javelin: "A light spear thrown in track-and-field.",
  kaleidoscope: "A tube you look through that shows shifting colorful patterns.",
  labyrinth: "A complicated maze.",
  lagoon: "A shallow pool of water separated from the sea.",
  lighthouse: "A tower with a light that guides ships at night.",
  lullaby: "A soft song to help a baby fall asleep.",
  manuscript: "A handwritten or original copy of a book or document.",
  marathon: "A 26-mile foot race — or any long, grueling effort.",
  masquerade: "A party where people wear masks and costumes; a disguise.",
  menagerie: "A collection of wild animals kept for show.",
  meteor: "A streak of light from a space rock burning up — a shooting star.",
  mirage: "A trick of the eye, like water shimmering on a hot road.",
  moat: "A water-filled ditch around a castle.",
  monastery: "A place where monks live.",
  monsoon: "A season of heavy rain and wind.",
  mosaic: "A picture made from many small tiles or pieces.",
  nomad: "A person who roams instead of living in one place.",
  nostalgia: "A warm, longing feeling for the past.",
  oasis: "A green, watery spot in the desert.",
  obelisk: "A tall, four-sided stone pillar that tapers to a point.",
  observatory: "A building with telescopes for watching the stars.",
  orchard: "A field of fruit trees.",
  paradox: "A statement that contradicts itself but may be true.",
  pendulum: "A weight that swings back and forth, like in a grandfather clock.",
  periscope: "A tube with mirrors for seeing above you, used in submarines.",
  pilgrimage: "A journey to a sacred or meaningful place.",
  pinnacle: "The highest point — a peak.",
  quarantine: "Being kept apart to stop the spread of disease.",
  quarry: "A pit where stone is dug out of the ground.",
  quicksand: "Loose wet sand that pulls you down if you step in it.",
  ransom: "Money demanded to free a captive.",
  relic: "An old object that survived from the past.",
  riddle: "A puzzling question with a clever answer.",
  sabotage: "Deliberately wrecking or undermining something.",
  sanctuary: "A safe, protected place.",
  scaffold: "A temporary frame workers stand on to reach high places.",
  serpent: "A snake.",
  silhouette: "A dark outline of a shape against a lighter background.",
  smuggler: "Someone who sneaks goods across borders illegally.",
  stalemate: "A standstill where neither side can win.",
  stowaway: "Someone who hides on a ship or plane to travel for free.",
  summit: "The very top of a mountain — or a top-level meeting.",
  sundial: "A clock that tells time by the shadow of the sun.",
  tapestry: "A heavy woven cloth with a picture or design.",
  telescope: "A tube that makes far-away things look closer.",
  tornado: "A violent funnel of spinning wind.",
  trapeze: "A swinging bar acrobats perform on.",
  treason: "Betraying your own country.",
  tribunal: "A court or panel that passes judgment.",
  tsunami: "A giant ocean wave caused by an earthquake.",
  tundra: "A cold, treeless plain where the ground stays frozen.",
  turbulence: "Rough, bumpy air that shakes a plane.",
  undertow: "A strong current pulling water back out under the waves.",
  vertigo: "A dizzy, spinning sensation, often from heights.",
  vortex: "A whirling mass that pulls things to its center, like a whirlpool.",
  voyage: "A long journey, especially by sea.",
  wilderness: "Wild, untamed natural land.",
  windmill: "A tower with sails that uses wind to grind grain or pump water.",
  zeppelin: "A huge rigid airship — a blimp.",
};

export function getWordDescription(word: string): string | undefined {
  return WORD_DESCRIPTIONS[word.toLowerCase()];
}
